accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from . import views as core_views

app_name='accounts'
urlpatterns = [
    path('homepage', views.homepage, name='homepage'),
    path('newuser', views.user_new, name='user_new'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

newsmonitor/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('source.urls')),
    path('', include('story.urls')),
    path('', include('accounts.urls')),
]

story/urls.py
from django.urls import path
from . import views

app_name='story'
urlpatterns = [
path('story/<int:id>/',views.view_stories, name='story'),
path('newsfeed', views.newsfeed, name='newsfeed'),
]

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django import forms


class Profile(models.Model):
    username = models.CharField(max_length=200,unique=True)
    birth_date = models.DateField(null=True, blank=True)
    password = models.CharField('Password', max_length=100)
    email = models.EmailField( max_length=100)

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth import authenticate,login,logout,get_user_model

user=get_user_model()

class SignUpForm(forms.ModelForm):
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = Profile
        fields = ('username', 'password', 'email' ,'birth_date' )

class LogInForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('username','password')

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from accounts.forms import SignUpForm, LogInForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.template import loader

def user_new(request):
    p= SignUpForm(request.POST or None)
    if p.is_valid():
        p.save()
        messages.success(request,'Registration Successfull')
        return HttpResponseRedirect('http://localhost:8000')
    context= {'form':p}
    return render(request, 'accounts/signup.html', context)

def login(request):
    form = LogInForm(request.POST or None)
    if form.is_valid():
       username = form.username
       password=str(form.cleaned_data['password'])
       user = authenticate(username=username, password=password)
       user.backend='django.contrib.auth.backends.ModelBackend'
       if user is not None:
           login(request, user)
           return HttpResponseRedirect('http://localhost:8000/source')
    return render(request, 'accounts/login.html', {'form': form})

def homepage(request):
    #template = loader.get_template('home.html')
    return render(request, 'accounts/home.html')

def logout(request):
    return render(request,' accounts/')

'''def login(self,request):
    form = LogInForm(request.POST or None)
    if form.is_valid():
        #text=form.cleaned_data['post']
        username = form.cleaned_data.get("Username")
        password = form.cleaned_data.get("Password")

        user = authenticate(username=username, password=password)
        if not user:
            raise form.ValidationError("This user does not exist")
            return render(request,self.signin.html)
        else:
            return render(request,self.signin.html)
    else:
        return render(request, 'accounts/login.html')'''

accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">  
    <title>{% block title %}Landing Page | News Monitor{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>Welcome to the News Monitor</h1>
     <!----> {% if user.is_authenticated %}
        <h2><a href="{% url 'accounts:logout' %}">logout</a></h2>
     <!----> {% else %}
        <h2><a href="{% url 'accounts:login' %}">login</a> / <a href="{% url 'accounts:user_new' %}">signup</a></h2>
      <!---->{% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

accounts/templates/accounts/login.html
<html>
<title>User Login | Login</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">
<body>
{% block content %}
<a href="http://localhost:8000" style="font-size: 22px;">Home</a>
    <h1>Login User</h1>
    <form method="POST" class="post-form" action="{% url 'accounts:login'%}"><h3>
        {% csrf_token %}
        {{ form.as_p }}</h3>
        <button type="submit">Login</button>
    </form>
{% endblock %}
</body>
<div>
<footer> Made with &hearts; by Arpit</footer>
</div>
</html>

accounts/templates/accounts/signup.html
<html>
<title>Enter User Details | SIGNUP</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">
<body>
{% block content %}
<a href="http://localhost:8000" style="font-size: 22px;">Home</a>
    <h1>Add New User</h1>
    <form method="POST" class="post-form" action="{% url 'accounts:user_new'%}"><h3>
        {% csrf_token %}
        {{ form.as_p }}</h3>
        <button type="submit">Save</button>
    </form>
{% endblock %}
</body>
<div>
<footer> Made with &hearts; by Arpit</footer>
</div>
</html>